blank_issues_enabled: false
contact_links:
  - name: Basin Documentation
    url: https://basin.app/docs/core
    about: Check our documentation for answers to common questions
  - name: Basin Discord Community
    url: https://discord.gg/rU4tSyhXXU
    about: Join our Discord server to chat with the community and get help
  - name: GitHub Discussions
    url: https://github.com/orgs/usebasin/discussions
    about: For general questions and discussions about Basin
  - name: Support Basin
    url: https://github.com/sponsors/andrejsshell
    about: Help keep Basin maintained and evolving